CREATE TABLE BRANDS
(
    BRAND_ID   INT PRIMARY KEY,
    BRAND_NAME VARCHAR(50) NOT NULL
);

CREATE TABLE PRICING
(
    PRICE_LIST         INT PRIMARY KEY,
    BRAND_ID   INT            NOT NULL,
    START_DATE TIMESTAMP      NOT NULL,
    END_DATE   TIMESTAMP      NOT NULL,
    PRODUCT_ID INT            NOT NULL,
    PRIORITY   INT            NOT NULL,
    PRICE      DECIMAL(10, 2) NOT NULL,
    CURR       VARCHAR(3)     NOT NULL,
    CONSTRAINT FK_PRICING_BRAND_ID FOREIGN KEY (BRAND_ID) REFERENCES BRANDS (BRAND_ID)
);


